apiVersion: apps/v1
kind: Deployment
metadata:
  name: ogo-deployment
  labels:
    app: ogo 
spec:
  selector:
    matchLabels:
      app: ogo 
  replicas: 2
  template:
    metadata:
      labels:
        app: ogo 
    spec:
      containers:
      - name: ogo
        image: ogo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5234

